if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins {{{

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'sainnhe/gruvbox-material'
Plug 'sheerun/vim-polyglot'
Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' }
Plug 'rafi/awesome-vim-colorschemes'
Plug 'SirVer/ultisnips'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
call plug#end()

"}}}

let mapleader=" "

set termguicolors
colorscheme gruvbox-material
set incsearch
set ignorecase smartcase
set hidden
set showcmd
set wildmenu
set backspace=indent,eol,start
set shiftwidth=4 tabstop=4 softtabstop=4 expandtab autoindent smartindent
set nu rnu
set ttimeoutlen=100
set updatetime=1000
set mouse=a
set nrformats-=octal
set history=200
set clipboard=unnamedplus
set splitbelow splitright

let g:tex_flavor = "latex"

" Shortcutting split navigation, saving a keypress:
	map <C-h> <C-w>h
	map <C-j> <C-w>j
	map <C-k> <C-w>k
	map <C-l> <C-w>l

" Don't use Ex mode, use Q for formatting.
map Q g

" To avoid deleting text when using Ctrl-U in insert mode
inoremap <C-U> <C-G>u<C-U>

" UltiSnips Settings
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetDirectories=['~/.vim/UltiSnips']

" LLP settings
let g:livepreview_previewer = 'zathura'

" Deoplet settings
let g:deoplete#enable_at_startup = 1

" VIMRC {{{

nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC <bar> :doautocmd BufRead<CR>

"}}}
set t_ut=""
